/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Examen;

import java.awt.Color;
import java.awt.print.PrinterException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author DELL
 */
public class UI_etudiant extends javax.swing.JFrame {

    /**
     * Creates new form UI_etudiant
     */
    public UI_etudiant() {
        initComponents();
        Examen.Generalites.Centrer_Fenetres(this);
        charger_tableau(tab_etudiant);
       this.setTitle("Application de Gestion du Paiement de Minerval");
        Deplace_objet();
        jPanel1.setFocusable(true);
        
        
    }
    static Etudiant et=null;
    public void charger_tableau(JTable tab)
    {
        ResultSet resu=Examen.Connect.extraireData("select *from etudiant");
        int size,i=0;
        size=Examen.Generalites.getResultSetRowCount(resu);
        String[] titres={"ID","Nom","Prenom","Numero carte"};
        String[][]data=new String[size][titres.length];
        if(resu!=null)
        {
            try {
                while(resu.next())
                {
                    data[i][0]=""+resu.getInt("etId");
                    data[i][1]=resu.getString("nom");
                    data[i][2]=resu.getString("prenom");
                    data[i][3]=resu.getString("num_carte");
                    
                    i++;
                }
                tab.setModel(new Model_table(data,titres));
            } catch (SQLException ex) {
                Logger.getLogger(UI_etudiant.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }
    public void charge_tab_rechercher(JTable tab)
    {
        ResultSet resulta=Examen.Connect.extraireData("select *from etudiant where num_carte='"+txt_rechercher.getText()+"'");
        int size,i=0;
        size=Examen.Generalites.getResultSetRowCount(resulta);
        String[]titres={"ID","Nom","Prenom","Numero carte"};
        String[][]data=new String[size][titres.length];
        if(resulta!=null)
        {
            try {
                while(resulta.next())
                {
                    data[i][0]=""+resulta.getString("etId");
                    data[i][1]=resulta.getString("nom");
                    data[i][2]=resulta.getString("prenom");
                    data[i][3]=resulta.getString("num_carte");
                    i++;
                }
            } catch (SQLException ex) {
                Logger.getLogger(UI_etudiant.class.getName()).log(Level.SEVERE, null, ex);
            }
            tab.setModel(new Model_table(data,titres));
        }
        else
            Examen.Generalites.Donner_info_User("Ce numero n'existe pas,Donc l'etudiant n'appartient pas dans la liste!");
    }
    public void Deplace_objet()
    {
        tab_etudiant.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
     
     public void valueChanged(ListSelectionEvent e) {
      int index_ligne=-1;
      index_ligne=tab_etudiant.getSelectedRow();
      if(index_ligne==-1)
          return;
      txt_nom.setForeground(new Color(0,0,0));
      txt_prenom.setForeground(new Color(0,0,0));
       txt_carte.setForeground(new Color(0,0,0));
    
      bt_enregistrer.setEnabled(false);
     
     txt_nom.setText(tab_etudiant.getValueAt(index_ligne,1).toString());
     txt_prenom.setText(tab_etudiant.getValueAt(index_ligne,2).toString());
     txt_carte.setText(tab_etudiant.getValueAt(index_ligne,3).toString());
     if(et==null)
         et=new Etudiant();
     et.setEtId(Integer.parseInt(tab_etudiant.getValueAt(index_ligne,0).toString()));
     }
 });
        
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_nom = new javax.swing.JTextField();
        txt_prenom = new javax.swing.JTextField();
        txt_carte = new javax.swing.JTextField();
        bt_enregistrer = new javax.swing.JButton();
        bt_modifier = new javax.swing.JButton();
        bt_supprimer = new javax.swing.JButton();
        bt_actualiser = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_rechercher = new javax.swing.JTextField();
        bt_rechercher = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_etudiant = new javax.swing.JTable();
        bt_print = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        bt_histo = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Item_classe = new javax.swing.JMenuItem();
        Item_tranche = new javax.swing.JMenuItem();
        Item_et_cl = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Item_login = new javax.swing.JMenuItem();
        Item_fermer = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Enregistrement des etudiants");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nom:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Prenom:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Numero de carte:");

        txt_nom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_nom.setForeground(new java.awt.Color(102, 102, 102));
        txt_nom.setText("Tapez le nom ici");
        txt_nom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_nomFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_nomFocusLost(evt);
            }
        });
        txt_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomActionPerformed(evt);
            }
        });

        txt_prenom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_prenom.setForeground(new java.awt.Color(102, 102, 102));
        txt_prenom.setText("Tapez le prenom ici");
        txt_prenom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_prenomFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_prenomFocusLost(evt);
            }
        });

        txt_carte.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_carte.setForeground(new java.awt.Color(102, 102, 102));
        txt_carte.setText("Numero du carte ici");
        txt_carte.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_carteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_carteFocusLost(evt);
            }
        });

        bt_enregistrer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_enregistrer.setText("Enregistrer");
        bt_enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_enregistrerActionPerformed(evt);
            }
        });

        bt_modifier.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_modifier.setText("Modifier");
        bt_modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_modifierActionPerformed(evt);
            }
        });

        bt_supprimer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_supprimer.setText("Supprimer");
        bt_supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_supprimerActionPerformed(evt);
            }
        });

        bt_actualiser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_actualiser.setText("Actualiser");
        bt_actualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_actualiserActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Rechercher par carte:");

        txt_rechercher.setForeground(new java.awt.Color(102, 102, 102));
        txt_rechercher.setText("Tapez le numero carte ici");
        txt_rechercher.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_rechercherFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_rechercherFocusLost(evt);
            }
        });

        bt_rechercher.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_rechercher.setIcon(new javax.swing.ImageIcon("E:\\Logos\\recher.JPG")); // NOI18N
        bt_rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_rechercherActionPerformed(evt);
            }
        });

        tab_etudiant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nom", "Prenom", "Numero de carte"
            }
        ));
        tab_etudiant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_etudiantMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab_etudiant);

        bt_print.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_print.setText("Imprimer");
        bt_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_printActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon("E:\\Logos\\ult.jfif")); // NOI18N
        jLabel6.setText("jLabel6");

        bt_histo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_histo.setText("Historique");
        bt_histo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_histoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txt_carte, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bt_supprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_enregistrer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(bt_print, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bt_modifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_actualiser, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                            .addComponent(bt_histo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_carte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_enregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_actualiser, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_print, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_histo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(txt_rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bt_rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jMenu1.setText("Enregistrer");

        Item_classe.setText("Classe");
        Item_classe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_classeActionPerformed(evt);
            }
        });
        jMenu1.add(Item_classe);

        Item_tranche.setText("Tranche");
        Item_tranche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_trancheActionPerformed(evt);
            }
        });
        jMenu1.add(Item_tranche);

        Item_et_cl.setText("Etudiant->Classe");
        Item_et_cl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_et_clActionPerformed(evt);
            }
        });
        jMenu1.add(Item_et_cl);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Retourner");

        Item_login.setText("Vers Login");
        Item_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_loginActionPerformed(evt);
            }
        });
        jMenu2.add(Item_login);

        Item_fermer.setText("Fermer");
        Item_fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_fermerActionPerformed(evt);
            }
        });
        jMenu2.add(Item_fermer);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Historique");

        jMenuItem1.setText("Etudiant");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_enregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_enregistrerActionPerformed
        // TODO add your handling code here:
        if(txt_nom.getText().trim().equalsIgnoreCase("")||txt_nom.getText().trim().equalsIgnoreCase("Tapez le nom ici")||txt_prenom.getText().trim().equalsIgnoreCase("")||txt_prenom.getText().trim().equalsIgnoreCase("Tapez le prenom ici")||txt_carte.getText().trim().equalsIgnoreCase("")||txt_carte.getText().trim().equalsIgnoreCase("Numero du carte ici"))
        {
            Examen.Generalites.Donner_info_User("Saisissez d abord les donnes à enregistrer");
            return;
        }
       
        else
        {
            Etudiant et=null;
            et=new Etudiant();
            et.setNom(txt_nom.getText());
            et.setPrenom(txt_prenom.getText());
            et.setCarte(txt_carte.getText());
            if(et.Enregistre_etudiant()>0)
            {
                
                Examen.Generalites.Donner_info_User("Votre enregistrement est reussi!");
                
                
                
                charger_tableau(tab_etudiant);
                txt_nom.setForeground(new Color(102,102,102));
                txt_prenom.setForeground(new Color(102,102,102));
                txt_carte.setForeground(new Color(102,102,102));
                txt_nom.setText("Tapez le nom ici");
                txt_prenom.setText("Tapez le prenom ici");
                txt_carte.setText("Numero du carte ici");
                
            }
            else
                Examen.Generalites.Donner_info_User("Echec d'enregistrement!");
                txt_nom.setForeground(new Color(102,102,102));
                txt_prenom.setForeground(new Color(102,102,102));
                txt_carte.setForeground(new Color(102,102,102));
                txt_nom.setText("Tapez le nom ici");
                txt_prenom.setText("Tapez le prenom ici");
                txt_carte.setText("Numero du carte ici");
        }
    }//GEN-LAST:event_bt_enregistrerActionPerformed

    private void txt_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomActionPerformed

    private void tab_etudiantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_etudiantMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_tab_etudiantMouseClicked

    private void bt_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modifierActionPerformed
        // TODO add your handling code here:
        if(txt_nom.getText().trim().equalsIgnoreCase("")||txt_nom.getText().trim().equalsIgnoreCase("Tapez le nom ici")||txt_prenom.getText().trim().equalsIgnoreCase("")||txt_prenom.getText().trim().equalsIgnoreCase("Tapez le prenom ici")||txt_carte.getText().trim().equalsIgnoreCase("")||txt_carte.getText().trim().equalsIgnoreCase("Numero du carte ici"))
        {
           Examen.Generalites.Donner_info_User("Selectionner d 'abord dans le tableau la ligne à modifier!");
            return;
        }
       try{
        et.setNom(txt_nom.getText());
        et.setPrenom(txt_prenom.getText());
        et.setCarte(txt_carte.getText());
        if(et.modifier_etudiant()>0)
        {
            
            Examen.Generalites.Donner_info_User("La modification est resussie!");
            
            charger_tableau(tab_etudiant);
             txt_nom.setForeground(new Color(102,102,102));
                txt_prenom.setForeground(new Color(102,102,102));
                txt_carte.setForeground(new Color(102,102,102));
            txt_nom.setText("Tapez le nom ici");
        txt_prenom.setText("Tapez le prenom ici");
        txt_carte.setText("Numero du carte ici");
        }
        else
        {
            Examen.Generalites.Donner_info_User("Echec de modification!");
             txt_nom.setForeground(new Color(102,102,102));
                txt_prenom.setForeground(new Color(102,102,102));
                txt_carte.setForeground(new Color(102,102,102));
            txt_nom.setText("Tapez le nom ici");
        txt_prenom.setText("Tapez le prenom ici");
        txt_carte.setText("Numero du carte ici");
        }
        bt_enregistrer.setEnabled(true);
       
       }catch(NullPointerException e){
           Examen.Generalites.Donner_info_User("Selectionner d 'abord dans le tableau la ligne à modifier!");
       }catch(NumberFormatException e){
            Examen.Generalites.Donner_info_User("Selectionner d'abord dans le tableau la ligne à modifier!");
        }
       
    }//GEN-LAST:event_bt_modifierActionPerformed

    private void bt_supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_supprimerActionPerformed
        // TODO add your handling code here:
        if(txt_nom.getText().trim().equalsIgnoreCase("")||txt_nom.getText().trim().equalsIgnoreCase("Tapez le nom ici")||txt_prenom.getText().trim().equalsIgnoreCase("")||txt_prenom.getText().trim().equalsIgnoreCase("Tapez le prenom ici")||txt_carte.getText().trim().equalsIgnoreCase("")||txt_carte.getText().trim().equalsIgnoreCase("Numero du carte ici"))
        {
           Examen.Generalites.Donner_info_User("Selectionner d'abord dans le tableau la ligne à supprimer!");
            return;
        }
        try{
        if(et.supprime_etudiant()>0)
        {
           
           Examen.Generalites.Donner_info_User("la suppression est reussie!");
           
           charger_tableau(tab_etudiant);
            txt_nom.setForeground(new Color(102,102,102));
                txt_prenom.setForeground(new Color(102,102,102));
                txt_carte.setForeground(new Color(102,102,102));
           txt_nom.setText("Tapez le nom ici");
        txt_prenom.setText("Tapez le prenom ici");
        txt_carte.setText("Numero du carte ici");
           bt_enregistrer.setEnabled(true);
        }
        else
            Examen.Generalites.Donner_info_User("Echec de la suppression!");
        bt_enregistrer.setEnabled(true);
       
        }catch(NullPointerException e){
            Examen.Generalites.Donner_info_User("Selectionner d'abord dans le tableau la ligne à supprimer!");
        }catch(NumberFormatException e){
            Examen.Generalites.Donner_info_User("Selectionner d'abord dans le tableau la ligne à supprimer!");
        }
        
    }//GEN-LAST:event_bt_supprimerActionPerformed

    private void bt_actualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_actualiserActionPerformed
        // TODO add your handling code here:
        
        charger_tableau(tab_etudiant);
         txt_nom.setForeground(new Color(102,102,102));
                txt_prenom.setForeground(new Color(102,102,102));
                txt_carte.setForeground(new Color(102,102,102));
        txt_nom.setText("Tapez le nom ici");
        txt_prenom.setText("Tapez le prenom ici");
        txt_carte.setText("Numero du carte ici");
        txt_rechercher.setText("Tapez le numero carte ici");
      
    }//GEN-LAST:event_bt_actualiserActionPerformed

    private void bt_rechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_rechercherActionPerformed
        // TODO add your handling code here:
        if(txt_rechercher.getText().trim().equalsIgnoreCase("")||txt_rechercher.getText().trim().equalsIgnoreCase("Tapez le numero carte ici"))
        {
            Examen.Generalites.Donner_info_User("Saisissez le numero du carte d'etudiant à chercher!");
            return;
        }
        else{
        charge_tab_rechercher(tab_etudiant);
        txt_rechercher.setText("");
        }
        
    }//GEN-LAST:event_bt_rechercherActionPerformed

    private void bt_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_printActionPerformed
        // TODO add your handling code here:
             try {
            // TODO add your handling code here:
            MessageFormat header=new MessageFormat("Liste des etudiants à universite du lac Tanganyika(ULT)");
            MessageFormat footer=new MessageFormat("");
            Boolean a=tab_etudiant.print(JTable.PrintMode.NORMAL, header,footer);
            
            if(a)
            {
                Examen.Generalites.Donner_info_User("OK,l'Impression est finie");
                
            }
            else
            {
                Examen.Generalites.Donner_info_User("Impression est annulé........");
            }} catch (PrinterException ex) {
            Logger.getLogger(UI_direction.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bt_printActionPerformed

    private void Item_fermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_fermerActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_Item_fermerActionPerformed

    private void Item_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_loginActionPerformed
        // TODO add your handling code here:
        UI_authentifier  a=new UI_authentifier ();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Item_loginActionPerformed

    private void Item_classeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_classeActionPerformed
        // TODO add your handling code here:
        UI_classe b=new UI_classe();
        b.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Item_classeActionPerformed

    private void Item_trancheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_trancheActionPerformed
        // TODO add your handling code here:
        UI_tranche t=new UI_tranche();
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Item_trancheActionPerformed

    private void Item_et_clActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_et_clActionPerformed
        // TODO add your handling code here:
        UI_etud_class e=new UI_etud_class();
        e.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Item_et_clActionPerformed

    private void bt_histoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_histoActionPerformed
        // TODO add your handling code here:
        if(txt_nom.getText().trim().equalsIgnoreCase("")||txt_nom.getText().trim().equalsIgnoreCase("Tapez le nom ici")||txt_prenom.getText().trim().equalsIgnoreCase("")||txt_prenom.getText().trim().equalsIgnoreCase("Tapez le prenom ici")||txt_carte.getText().trim().equalsIgnoreCase("")||txt_carte.getText().trim().equalsIgnoreCase("Numero du carte ici"))
        {
            Examen.Generalites.Donner_info_User("Selectionner d'abord dans le tableau le client à maitre dans l'Historique");
            return;
        }
        else{
        Examen.Connect.modifierDB("insert into historique( nom,prenom,num_carte)values('"+txt_nom.getText()+"','"+txt_prenom.getText()+"','"+txt_carte.getText()+"')");
        Examen.Connect.modifierDB("delete from etudiant where num_carte='"+txt_carte.getText()+"'");
        
        Examen.Generalites.Donner_info_User("Vous mettez cet etudiant dans l'historique!");
         txt_nom.setForeground(new Color(102,102,102));
                txt_prenom.setForeground(new Color(102,102,102));
                txt_carte.setForeground(new Color(102,102,102));
           txt_nom.setText("Tapez le nom ici");
        txt_prenom.setText("Tapez le prenom ici");
        txt_carte.setText("Numero du carte ici");
         charger_tableau(tab_etudiant);
         charger_tableau(tab_etudiant);
         bt_enregistrer.setEnabled(true);
        }
    }//GEN-LAST:event_bt_histoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
          UI_historique h=new UI_historique();
        h.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void txt_nomFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nomFocusGained
        // TODO add your handling code here:
        if(txt_nom.getText().equals("Tapez le nom ici"))
        {
            txt_nom.setText("");
            txt_nom.setForeground(new Color(0,0,0));
            
        }
    }//GEN-LAST:event_txt_nomFocusGained

    private void txt_nomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nomFocusLost
        // TODO add your handling code here:
        if(txt_nom.getText().equals(""))
        {
            txt_nom.setText("Tapez le nom ici");
            txt_nom.setForeground(new Color(102,102,102));
          
        }
         else if(txt_nom.getText()!=""&&txt_nom.getText()!="Tapez le nom ici")
         {
             txt_nom.setForeground(new Color(0,0,0));
         }
        
    }//GEN-LAST:event_txt_nomFocusLost

    private void txt_prenomFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_prenomFocusGained
        // TODO add your handling code here:
        if(txt_prenom.getText().equals("Tapez le prenom ici"))
        {
            txt_prenom.setText("");
            txt_prenom.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txt_prenomFocusGained

    private void txt_prenomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_prenomFocusLost
        // TODO add your handling code here:
        if(txt_prenom.getText().equals(""))
        {
            txt_prenom.setText("Tapez le prenom ici");
            txt_prenom.setForeground(new Color(102,102,102));
        }
         else if(txt_prenom.getText()!=""&&txt_prenom.getText()!="Tapez le prenom ici")
         {
             txt_prenom.setForeground(new Color(0,0,0));
         }
    }//GEN-LAST:event_txt_prenomFocusLost

    private void txt_carteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_carteFocusGained
        // TODO add your handling code here:
         if(txt_carte.getText().equals("Numero du carte ici"))
        {
            txt_carte.setText("");
            txt_carte.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txt_carteFocusGained

    private void txt_carteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_carteFocusLost
        // TODO add your handling code here:
         if(txt_carte.getText().equals(""))
        {
            txt_carte.setText("Numero du carte ici");
            txt_carte.setForeground(new Color(102,102,102));
        }
         else if(txt_carte.getText()!=""&&txt_carte.getText()!="Numero du carte ici")
         {
             txt_carte.setForeground(new Color(0,0,0));
         }
    }//GEN-LAST:event_txt_carteFocusLost

    private void txt_rechercherFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_rechercherFocusGained
        // TODO add your handling code here:
        if(txt_rechercher.getText().equals("Tapez le numero carte ici"))
        {
            txt_rechercher.setText("");
            txt_rechercher.setForeground(new Color(0,0,0));
        }
         
    }//GEN-LAST:event_txt_rechercherFocusGained

    private void txt_rechercherFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_rechercherFocusLost
        // TODO add your handling code here:
          if(txt_rechercher.getText().equals(""))
        {
            txt_rechercher.setText("Tapez le numero carte ici");
            txt_rechercher.setForeground(new Color(102,102,102));
        }
         else if(txt_rechercher.getText()!=""&&txt_rechercher.getText()!="Tapez le numero carte ici")
         {
             txt_rechercher.setForeground(new Color(0,0,0));
         }
    }//GEN-LAST:event_txt_rechercherFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_etudiant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Item_classe;
    private javax.swing.JMenuItem Item_et_cl;
    private javax.swing.JMenuItem Item_fermer;
    private javax.swing.JMenuItem Item_login;
    private javax.swing.JMenuItem Item_tranche;
    private javax.swing.JButton bt_actualiser;
    private javax.swing.JButton bt_enregistrer;
    private javax.swing.JButton bt_histo;
    private javax.swing.JButton bt_modifier;
    private javax.swing.JButton bt_print;
    private javax.swing.JButton bt_rechercher;
    private javax.swing.JButton bt_supprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tab_etudiant;
    private javax.swing.JTextField txt_carte;
    private javax.swing.JTextField txt_nom;
    private javax.swing.JTextField txt_prenom;
    private javax.swing.JTextField txt_rechercher;
    // End of variables declaration//GEN-END:variables
}
