/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Examen;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author DELL
 */
public class UI_tranche extends javax.swing.JFrame {

    /**
     * Creates new form UI_tranche
     */
    public UI_tranche() {
        initComponents();
        Examen.Generalites.Centrer_Fenetres(this);
        charger_tab_tranche(tab_tranche);
        bt_enregistre.setEnabled(true);
        bt_supprime.setEnabled(false);
        deplace_tranche();
        jPanel1.setFocusable(true);
        this.setTitle("Application de Gestion du Paiement de Minerval");
        
    }
    Tranches tr=null;
    public void charger_tab_tranche(JTable tab)
    {
        ResultSet resul=Examen.Connect.extraireData("select *from tranche");
        int index,i=0;
        index=Examen.Generalites.getResultSetRowCount(resul);
        String[] titres={"trID","Nom du tranche"};
        String[][]data=new String[index][titres.length];
        if(resul!=null)
        {
            try {
                while(resul.next())
                {
                    data[i][0]=""+resul.getInt("trId");
                    data[i][1]=resul.getString("nom_tra");
                    i++;
                }
                tab.setModel(new Model_table(data,titres));
            } catch (SQLException ex) {
                Logger.getLogger(UI_tranche.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
    }
    public void deplace_tranche()
    {
        tab_tranche.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            @Override
         
            public void valueChanged(ListSelectionEvent e) {
             bt_enregistre.setEnabled(false);
               bt_supprime.setEnabled(true);
                int index_line=-1;
                index_line=tab_tranche.getSelectedRow();
                if(index_line==-1)
                    return;
                txt_tranche.setForeground(new Color(0,0,0));
                txt_tranche.setText(tab_tranche.getValueAt(index_line,1).toString());
                if(tr==null)
                    tr=new Tranches();
                tr.setTrId(Integer.parseInt(tab_tranche.getValueAt(index_line, 0).toString()));
            }
            
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_tranche = new javax.swing.JTextField();
        bt_enregistre = new javax.swing.JButton();
        bt_supprime = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_tranche = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Item_etudiant = new javax.swing.JMenuItem();
        Item_classe = new javax.swing.JMenuItem();
        Item_et_cl = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Item_login = new javax.swing.JMenuItem();
        Item_fermer = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Enregistrement des Tranches");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nom du tranche:");

        txt_tranche.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_tranche.setForeground(new java.awt.Color(102, 102, 102));
        txt_tranche.setText("Tapez le nom du tranche ici");
        txt_tranche.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_trancheFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_trancheFocusLost(evt);
            }
        });

        bt_enregistre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_enregistre.setText("Enregistrer");
        bt_enregistre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_enregistreActionPerformed(evt);
            }
        });

        bt_supprime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_supprime.setText("Supprimer");
        bt_supprime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_supprimeActionPerformed(evt);
            }
        });

        tab_tranche.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tab_tranche);

        jLabel3.setIcon(new javax.swing.ImageIcon("E:\\Logos\\ult.jfif")); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_tranche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_enregistre, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_supprime, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_tranche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_enregistre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_supprime, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("Enregistrer");

        Item_etudiant.setText("Etudiant");
        Item_etudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_etudiantActionPerformed(evt);
            }
        });
        jMenu1.add(Item_etudiant);

        Item_classe.setText("Classe");
        Item_classe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_classeActionPerformed(evt);
            }
        });
        jMenu1.add(Item_classe);

        Item_et_cl.setText("Etudiant->Classe");
        Item_et_cl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_et_clActionPerformed(evt);
            }
        });
        jMenu1.add(Item_et_cl);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Retourner");

        Item_login.setText("Vers Login");
        Item_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_loginActionPerformed(evt);
            }
        });
        jMenu2.add(Item_login);

        Item_fermer.setText("Fermer");
        Item_fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_fermerActionPerformed(evt);
            }
        });
        jMenu2.add(Item_fermer);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Historique");

        jMenuItem1.setText("Etudiant");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_enregistreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_enregistreActionPerformed
        // TODO add your handling code here:
        if(txt_tranche.getText().trim().equalsIgnoreCase("")||txt_tranche.getText().trim().equalsIgnoreCase("Tapez le nom du tranche ici"))
        {
            Examen.Generalites.Donner_info_User("Saisissez d'abord le nom de la tranche");
            return;
        }
        else
        {
            tr=new Tranches();
            tr.setNom(txt_tranche.getText());
            if(tr.enregistre_tranche()>0)
            {
                
                Examen.Generalites.Donner_info_User("L'enregistrement d'une tranche est reussie!");
                charger_tab_tranche(tab_tranche);
                txt_tranche.setForeground(new Color(102,102,102));
                txt_tranche.setText("Tapez le nom du tranche ici");
            }
            else
                Examen.Generalites.Donner_info_User("Echec de l'enregistrement!");
                txt_tranche.setForeground(new Color(102,102,102));
                txt_tranche.setText("Tapez le nom du tranche ici");
            
             bt_enregistre.setEnabled(true);
             bt_supprime.setEnabled(false);


        }
    }//GEN-LAST:event_bt_enregistreActionPerformed

    private void bt_supprimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_supprimeActionPerformed
        // TODO add your handling code here:
        if(txt_tranche.getText().trim().equalsIgnoreCase("")||txt_tranche.getText().trim().equalsIgnoreCase("Tapez le nom du tranche ici"))
        {
            Examen.Generalites.Donner_info_User("Selectionner dans le tableau la tranche à modifier");
            return;
        }
        else{
        if(tr.supprime_tranche()>0)
        {
            

            Examen.Generalites.Donner_info_User("la suppression d'une tranche est effectuee!");
            charger_tab_tranche(tab_tranche);
            txt_tranche.setForeground(new Color(102,102,102));
            txt_tranche.setText("Tapez le nom du tranche ici");
        }
        else
            Examen.Generalites.Donner_info_User("Ëchec de la suppression");
        
          
         bt_enregistre.setEnabled(true);
         bt_supprime.setEnabled(false);
        }
    }//GEN-LAST:event_bt_supprimeActionPerformed

    private void Item_etudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_etudiantActionPerformed
        // TODO add your handling code here:
        UI_etudiant e=new UI_etudiant();
        e.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Item_etudiantActionPerformed

    private void Item_classeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_classeActionPerformed
        // TODO add your handling code here:
        UI_classe c=new UI_classe();
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Item_classeActionPerformed

    private void Item_et_clActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_et_clActionPerformed
        // TODO add your handling code here:
        UI_etud_class et=new UI_etud_class();
        et.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Item_et_clActionPerformed

    private void Item_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_loginActionPerformed
        // TODO add your handling code here:
        UI_authentifier  d=new UI_authentifier ();
        d.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Item_loginActionPerformed

    private void Item_fermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_fermerActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
    }//GEN-LAST:event_Item_fermerActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
          UI_historique h=new UI_historique();
        h.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void txt_trancheFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_trancheFocusGained
        // TODO add your handling code here:
         if(txt_tranche.getText().equals("Tapez le nom du tranche ici"))
        {
            txt_tranche.setText("");
            txt_tranche.setForeground(new Color(0,0,0));
            
        }
       
    }//GEN-LAST:event_txt_trancheFocusGained

    private void txt_trancheFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_trancheFocusLost
        // TODO add your handling code here:
          if(txt_tranche.getText().equals(""))
        {
            txt_tranche.setText("Tapez le nom du tranche ici");
            txt_tranche.setForeground(new Color(102,102,102));
          
        }
         else if(txt_tranche.getText()!=""&&txt_tranche.getText()!="Tapez le nom du tranche ici")
         {
             txt_tranche.setForeground(new Color(0,0,0));
         }
    }//GEN-LAST:event_txt_trancheFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_tranche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_tranche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_tranche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_tranche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_tranche().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Item_classe;
    private javax.swing.JMenuItem Item_et_cl;
    private javax.swing.JMenuItem Item_etudiant;
    private javax.swing.JMenuItem Item_fermer;
    private javax.swing.JMenuItem Item_login;
    private javax.swing.JButton bt_enregistre;
    private javax.swing.JButton bt_supprime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tab_tranche;
    private javax.swing.JTextField txt_tranche;
    // End of variables declaration//GEN-END:variables
}
